# Generated by Django 5.2.6 on 2025-09-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hut_meal_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت')),
                ('categories', models.ManyToManyField(blank=True, to='hut_meal_category.productcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منو ها',
            },
        ),
    ]
