# Generated by Django 5.2.6 on 2025-09-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منو ها',
            },
        ),
    ]
