# Generated by Django 5.2.6 on 2025-09-30 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_menu', '0002_meals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'وعده', 'verbose_name_plural': 'وعده ها'},
        ),
        migrations.AddField(
            model_name='menu',
            name='meals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hut_meal_menu.meals', verbose_name='انتخاب وعده'),
            preserve_default=False,
        ),
    ]
