# Generated by Django 5.2.6 on 2025-09-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_menu', '0003_alter_meals_options_menu_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='meals',
        ),
        migrations.AddField(
            model_name='menu',
            name='meals',
            field=models.ManyToManyField(blank=True, to='hut_meal_menu.meals', verbose_name='انتخاب وعده'),
        ),
    ]
