# Generated by Django 5.2.6 on 2025-09-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_menu', '0004_remove_menu_meals_menu_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
