# Generated by Django 5.2.6 on 2025-09-17 17:57

import hut_meal_brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان در url')),
                ('image', models.ImageField(blank=True, null=True, upload_to=hut_meal_brand.models.upload_image, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند های محصولات',
            },
        ),
    ]
