# Generated by Django 5.2.6 on 2025-10-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hut_meal_blog', '0001_initial'),
        ('hut_meal_product', '0014_product_brand_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('blogs', models.ManyToManyField(blank=True, to='hut_meal_blog.blog', verbose_name='بلاگ ها ')),
                ('products', models.ManyToManyField(blank=True, to='hut_meal_product.product', verbose_name='محصولات ')),
            ],
            options={
                'verbose_name': 'برچسب / تگ',
                'verbose_name_plural': 'برچسب ها / تگ ها',
            },
        ),
    ]
