# Generated by Django 5.2.6 on 2025-09-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('link', models.CharField(max_length=100, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'دسته بندی ',
                'verbose_name_plural': 'دسته بندی های بلاگ ',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'دسته بندی ',
                'verbose_name_plural': 'دسته بندی های محصولات ',
            },
        ),
    ]
