# Generated by Django 5.2.6 on 2025-10-03 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_category', '0002_bl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bl',
            name='nn',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
