# Generated by Django 5.2.6 on 2025-10-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_category', '0003_bl_nn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bl',
        ),
    ]
