# Generated by Django 5.2.6 on 2025-10-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_category', '0004_delete_bl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
