# Generated by Django 5.2.6 on 2025-10-10 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_category', '0005_delete_blogcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('productcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hut_meal_category.productcategory')),
            ],
            options={
                'verbose_name': 'دسته بندی ',
                'verbose_name_plural': 'دسته بندی های بلاگ ',
            },
            bases=('hut_meal_category.productcategory',),
        ),
    ]
