# Generated by Django 5.2.6 on 2025-10-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hut_meal_Team', '0001_initial'),
        ('hut_meal_category', '0006_blogcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('st_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hut_meal_Team.st')),
                ('user', models.CharField(max_length=30)),
                ('user_description', models.CharField(max_length=90)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('visits', models.IntegerField(default=0, verbose_name='تعداد مشاهده')),
                ('categories', models.ManyToManyField(blank=True, to='hut_meal_category.blogcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
            bases=('hut_meal_Team.st',),
        ),
    ]
