# Generated by Django 5.2.6 on 2025-10-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hut_meal_Team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesRestaurant',
            fields=[
                ('st_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hut_meal_Team.st')),
            ],
            options={
                'verbose_name': 'ویژگی رستوران',
                'verbose_name_plural': 'ویژگی های رستوران',
            },
            bases=('hut_meal_Team.st',),
        ),
    ]
