# Generated by Django 5.2.6 on 2025-10-10 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_Team', '0001_initial'),
        ('hut_meal_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('st_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hut_meal_Team.st')),
                ('name', models.CharField(max_length=35)),
                ('skills', models.CharField(max_length=29)),
            ],
            options={
                'verbose_name': 'اسلایدر1',
                'verbose_name_plural': 'اسلایدرها 1',
            },
            bases=('hut_meal_Team.st',),
        ),
    ]
