# Generated by Django 5.2.6 on 2025-10-16 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_Team', '0001_initial'),
        ('hut_meal_setting', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderBlog',
            fields=[
                ('st_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hut_meal_Team.st')),
                ('link', models.CharField(max_length=100, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'اسلایدر بلاگ',
                'verbose_name_plural': 'اسلایدر های بلاگ',
            },
            bases=('hut_meal_Team.st',),
        ),
    ]
