# Generated by Django 5.2.6 on 2025-10-16 09:54

import django.db.models.deletion
import hut_meal_brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_Team', '0001_initial'),
        ('hut_meal_setting', '0003_sliderblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('st_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hut_meal_Team.st')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=hut_meal_brand.models.upload_image, verbose_name='تصویر لوگو')),
                ('title_image', models.CharField(max_length=30, verbose_name='title_image')),
                ('description_image', models.CharField(max_length=40, verbose_name='description_image')),
                ('link', models.CharField(max_length=100, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه اول ',
                'verbose_name_plural': 'تنظیمات صفحه اول',
            },
            bases=('hut_meal_Team.st',),
        ),
    ]
