# Generated by Django 5.2.6 on 2025-10-16 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_Team', '0001_initial'),
        ('hut_meal_setting', '0004_homepagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('st_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hut_meal_Team.st')),
                ('title2', models.CharField(max_length=60, verbose_name='title2')),
                ('title3', models.CharField(max_length=100, verbose_name='title3')),
                ('discount', models.IntegerField(verbose_name='discount')),
            ],
            options={
                'verbose_name': 'اسلایدر اصلی',
                'verbose_name_plural': 'اسلایدر اصلی',
            },
            bases=('hut_meal_Team.st',),
        ),
    ]
