# Generated by Django 5.2.6 on 2025-10-16 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_setting', '0005_mainslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='link',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='footer_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=110, verbose_name='footer_text '),
            preserve_default=False,
        ),
    ]
