# Generated by Django 5.2.6 on 2025-10-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_setting', '0006_remove_homepagesettings_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='footer_text',
            field=models.CharField(max_length=300, verbose_name='footer_text '),
        ),
    ]
