# Generated by Django 5.2.6 on 2025-10-30 04:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_setting', '0007_alter_homepagesettings_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=130, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
