# Generated by Django 5.2.6 on 2025-10-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
    ]
