# Generated by Django 5.2.6 on 2025-10-16 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_blog', '0001_initial'),
        ('hut_meal_comment', '0002_remove_comment_product'),
        ('hut_meal_product', '0014_product_brand_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hut_meal_comment.comment')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_blogs', to='hut_meal_blog.blog')),
            ],
            bases=('hut_meal_comment.comment',),
        ),
        migrations.CreateModel(
            name='CommentProduct',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hut_meal_comment.comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_products', to='hut_meal_product.product')),
            ],
            bases=('hut_meal_comment.comment',),
        ),
    ]
