# Generated by Django 5.2.6 on 2025-09-19 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_order', '0001_initial'),
        ('hut_meal_product', '0014_product_brand_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='i')),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hut_meal_order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hut_meal_product.product')),
            ],
            options={
                'verbose_name': 'جزئیات سیدخرید',
                'verbose_name_plural': 'جزئیات های سبد خرید',
            },
        ),
    ]
