# Generated by Django 5.2.6 on 2025-10-31 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_order', '0003_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
