# Generated by Django 5.2.6 on 2025-09-16 11:52

import django.db.models.deletion
import hut_meal_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to=hut_meal_product.models.upload_image, verbose_name='تصویر')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('visits', models.IntegerField(default=0, verbose_name='تعداد مشاهده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=hut_meal_product.models.upload_image_gallery, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hut_meal_product.product', verbose_name='انتخاب محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
