# Generated by Django 5.2.6 on 2025-09-16 13:20

import hut_meal_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان رنگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=hut_meal_product.models.upload_image_gallery, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان تخفیف')),
                ('percentage', models.IntegerField(verbose_name='درصد تخفیف %')),
            ],
            options={
                'verbose_name': 'تخیف',
                'verbose_name_plural': 'تخفیف ها',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان سایز')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز ها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='hut_meal_product.productcolor', verbose_name='رنگ'),
        ),
    ]
