# Generated by Django 5.2.6 on 2025-09-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_product', '0002_productcolor_productdiscount_productsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.DeleteModel(
            name='ProductDiscount',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
