# Generated by Django 5.2.6 on 2025-09-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_product', '0004_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان تخفیف')),
                ('percentage', models.IntegerField(verbose_name='درصد تخفیف %')),
            ],
            options={
                'verbose_name': 'تخیف',
                'verbose_name_plural': 'تخفیف ها',
            },
        ),
    ]
