# Generated by Django 5.2.6 on 2025-09-16 14:20

import hut_meal_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_product', '0005_productdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان رنگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=hut_meal_product.models.upload_image_gallery, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
    ]
