# Generated by Django 5.2.6 on 2025-09-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_product', '0006_productcolorr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductColorr',
            new_name='ProductColor',
        ),
    ]
