# Generated by Django 5.2.6 on 2025-09-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_product', '0007_rename_productcolorr_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='hut_meal_product.productcolor', verbose_name='رنگ'),
        ),
    ]
