# Generated by Django 5.2.6 on 2025-09-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_product', '0008_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='hut_meal_product.productsize', verbose_name='سایز'),
        ),
    ]
