# Generated by Django 5.2.6 on 2025-09-16 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_product', '0009_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hut_meal_product.productdiscount', verbose_name='درصد تخفیف %'),
            preserve_default=False,
        ),
    ]
