# Generated by Django 5.2.6 on 2025-09-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_product', '0010_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discountt',
        ),
    ]
