# Generated by Django 5.2.6 on 2025-09-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_product', '0011_rename_discount_product_discountt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discountt',
            new_name='discount',
        ),
    ]
