# Generated by Django 5.2.6 on 2025-09-16 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_product', '0012_rename_discountt_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='image',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='image_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='کد رنگ'),
            preserve_default=False,
        ),
    ]
