# Generated by Django 5.2.6 on 2025-09-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_brand', '0001_initial'),
        ('hut_meal_category', '0001_initial'),
        ('hut_meal_product', '0013_remove_productcolor_image_productcolor_image_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hut_meal_brand.productbrand', verbose_name='برند'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='hut_meal_category.productcategory', verbose_name='دسته بندی'),
        ),
    ]
