# Generated by Django 5.2.6 on 2025-10-30 05:26

import hut_meal_brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=hut_meal_brand.models.upload_image, verbose_name='تصویر'),
        ),
    ]
