# Generated by Django 5.2.6 on 2025-10-03 16:27

import django.db.models.deletion
import hut_meal_brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'درجه',
                'verbose_name_plural': 'درجه ها',
            },
        ),
        migrations.CreateModel(
            name='ST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=hut_meal_brand.models.upload_image, verbose_name='تصویر')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('st_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hut_meal_Team.st')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
            bases=('hut_meal_Team.st',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('st_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hut_meal_Team.st')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hut_meal_Team.degree')),
                ('skills', models.ManyToManyField(blank=True, to='hut_meal_Team.skill', verbose_name='مهارت')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ها ',
            },
            bases=('hut_meal_Team.st',),
        ),
    ]
