# Generated by Django 5.2.6 on 2025-09-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('table_number', models.IntegerField()),
                ('mnimum_seats', models.IntegerField()),
                ('maximum_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_res', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hut_meal_reservation.table')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hut_meal_reservation.time')),
            ],
        ),
    ]
