# Generated by Django 5.2.6 on 2025-09-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
