# Generated by Django 5.2.6 on 2025-09-22 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_reservation', '0003_reservation_table_reservation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Customer_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
