# Generated by Django 5.2.6 on 2025-09-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_reservation', '0004_reservation_customer_email_reservation_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=15, verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
