# Generated by Django 5.2.6 on 2025-10-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_reservation', '0005_table_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='active',
        ),
    ]
