# Generated by Django 5.2.6 on 2025-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut_meal_reservation', '0006_remove_reservation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
